import ProductImg from "@/public/assets/billing/billingImg.png";

export const orderList = [
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534123",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534124",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534125",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534126",
    orderDate: "4th May, 2023",
    quantity: 2,

    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534127",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534128",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534129",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534130",
    orderDate: "4th May, 2023",
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534131",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534132",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "failed",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534133",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "failed",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534134",
    orderDate: "4th May, 2023",
    quantity: 2,
    status: "failed",
  },
];
