import ProductImg from "@/public/assets/billing/billingImg.png";

export const orderList = [
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "pending",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "failed",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "failed",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    status: "failed",
  },
];
