import ProductImg from "@/public/assets/billing/billingImg.png";

export const orderList = [
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534122",
    orderDate: "4th May, 2023",
    quantity: 1,
    category: "orders",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534123",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "orders",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534124",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "orders",
    status: "in progress",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534125",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "orders",
    status: "in progress",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534126",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "orders",
    status: "in progress",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534127",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "orders",
    status: "delivered",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534128",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "returns",
    status: "cancelled",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534129",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "returns",
    status: "cancelled",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534130",
    orderDate: "4th May, 2023",
    category: "returns",
    status: "cancelled",
  },
  {
    productTitle: "Zara Twist Front Textured Slinky Ruched Midi Dress ",
    productImage: ProductImg,
    orderId: "1625534131",
    orderDate: "4th May, 2023",
    quantity: 2,
    category: "returns",
    status: "cancelled",
  },
];
