export const productSubCategoryData = {
  dresses: [
    "Casual dresses",
    "Formal dresses",
    "Maxi dresses",
    "Midi dresses",
    "Bodycon dresses",
    "Shift dresses",
    "Wrap dresses",
    "Skater dresses",
    "Shirt dresses",
    "Cocktail dresses",
  ],
  tops: [
    "Blouses",
    "T-shirts",
    "Tank tops",
    "Crop tops",
    "Sweatshirts",
    "Hoodies",
    "Sweaters",
    "Tunics",
    "Peplum tops",
    "Off-shoulder tops",
  ],
  bottoms: [
    "Jeans",
    "Pants",
    "Leggings",
    "Skirts",
    "Shorts",
    "Culottes",
    "Palazzo pants",
    "Wide-leg pants",
    "High-waisted pants",
    "Capris",
  ],
  activeWear: [
    "Sports bras",
    "Yoga pants",
    "Leggings",
    "Tank tops",
    "Athletic shorts",
    "Running jackets",
    "Sweatshirts",
    "Hoodies",
    "Cycling shorts",
    "Compression shorts",
  ],
  swimWear: [
    "One-piece swimsuits",
    "Bikinis",
    "Tankinis",
    "High-waisted swimsuits",
    "Monokinis",
    "Cover-ups",
    "Board shorts",
    "Rashguards",
    "Swim skirts",
    "Swim leggings",
  ],
  Outerwear: [
    "Coats",
    "ackets",
    "Blazers",
    "Trench coats",
    "Peacoats",
    "Parkas",
    "Puffer jackets",
    "Denim jackets",
    "Leather jackets",
    "Bomber jackets",
  ],
  shoes: [
    "Sneakers",
    "Boots",
    "Sandals",
    "Flats",
    "Heels",
    "Wedges",
    "Espadrilles",
    "Mules",
    "Loafers",
    "Oxfords",
  ],
  accessories: [
    "Jewelry (necklaces, earrings, bracelets, rings, etc.)",
    "Handbags (tote bags, cross-body bags, clutches, etc.)",
    "Scarves",
    "Hats (beanies, sun hats, baseball caps, etc.)",
    "Belts",
    "Sunglasses",
    "Gloves",
    "Socks",
    "Tights",
    "Wallets",
  ],
  lingerie: [
    "Bras",
    "Panties",
    "Lingerie sets",
    "Robes",
    "Camisoles",
    "Teddies",
    "Babydolls",
    "Bustiers",
    "Chemises",
    "Garter belts",
  ],
  plusSizeClothing: [
    "Plus size dresses",
    "Plus size tops",
    "Plus size bottoms",
    "Plus size swimwear",
    "Plus size activewear",
    "Plus size lingerie",
    "Plus size outerwear",
    "Plus size jumpsuits",
    "Plus size rompers",
    "Plus size skirts",
  ],
  hairAccessories: [
    "Hair bands",
    "Beads",
    "Bows",
    "Hair pins",
    "Hair clips",
    "Hair bonnets",
  ],
  handbags: [
    "Shoulder bag",
    "Crossbody bag",
    "Belt bag",
    "Tote bag",
    "Flap purse",
    "Satchel bag",
    "Clutch bag",
    "Bucket purse",
    "Duffle bag",
    "Sling bag",
    "Beach bag",
    "Laptop bag",
    "Baguette bag (minibags)",
    "Backpack purse",
    "Wallet",
  ],
};
